### ISSUE TITLE
[ethereal][moretrees]alias pour les birch

### ISSUE THREAD

**Issue by Grossam** [MT-Eurythmia/Eurythmia-Evolution#10]
Les deux types de bois ont exactement le même aspect. Ce serait pas mal de crée un alias pour pouvoir les stacker.

**Comment by paly2** [comment]
Corrigé dans https://github.com/MT-Eurythmia/Eurythmia-Evolution/commit/b14e34bb68aa19417b23838a759291e4183d0098 et dans https://github.com/MT-Eurythmia/Eurythmia-Evolution/commit/3071c7fcf8a611cca1051a9e96cd7d0bac9248b1 :-)
L'alias risque de générer des problèmes, dans ce cas n'hésite pas à rouvrir l'issue
