### ISSUE TITLE
[farming] Changement de dépôt

### ISSUE THREAD

**Issue by louisroyer** [MT-Eurythmia/Eurythmia-Evolution#12]
Il me semble que le dépôt que a été cloné pour le mod `farming redo` n’est plus mis à jour depuis 2015. Il faudrait peut être considérer d’utiliser le [dépôt upstream](https://notabug.org/TenPlus1/farming) qui est mieux maintenu et fournit la traduction fr et la compatibilité avec `toolranks` pour les houes.

**Comment by paly2** [comment]
Merci, le dépôt a été mis à jour, la nouvelle version sera en jeu dès le prochain reboot !
