### ISSUE TITLE
Mods avec traduction fr

### ISSUE THREAD

**Issue by louisroyer** [MT-Eurythmia/Eurythmia-Evolution#13]
Je suis en train de faire des PR pour ajouter les trads fr à certains mods qui sont utilisés sur le serveur. Si ça vous intéresse, voici une liste des mods sur lesquels j’ai proposé des changements et qui sont utilisés ici : 
- [toolranks](https://github.com/lisacvuk/minetest-toolranks/)
- [moreores](https://github.com/minetest-mods/moreores/)

J’ai aussi proposé un correctif pour un bug avec les noix de coco sur [moretrees](https://gitlab.com/VanessaE/moretrees/).

Des PR pas encore acceptées mais qui pourraient aussi vous intéresser : 
- [caverealms](https://github.com/HeroOfTheWinds/minetest-caverealms/pull/18) (d’ailleurs il manque le `.gitrepo` pour ce mod)
- morechest : 
    - minetest-mods/more_chests/pull/18 (edit: fusionnée upstream)
    - minetest-mods/more_chests/pull/19
- [basic_materials](https://gitlab.com/VanessaE/basic_materials/-/merge_requests/2) (edit: fusionnée upstream)
- technic, dont technic_chests
    - [traductions](https://github.com/minetest-mods/technic/pull/529)
    - [fix craft](https://github.com/minetest-mods/technic/pull/530)
- (edit) [plantlife (modpack)](https://gitlab.com/VanessaE/plantlife_modpack/-/merge_requests/5) (edit: fusionnée upstream)

**Comment by paly2** [comment]
Merci, je vais rapidement mettre à jour toolranks, moreores et moretrees pour appliquer les nouveaux changements. Je réfléchissais depuis quelque temps à passer la langue du serveur en français, puisque la plupart des joueurs sont français et qu'ils sont nombreux à avoir des difficultés à comprendre les textes en anglais, je pense que le ferai en même temps.

**Comment by louisroyer** [comment]
Avec la nouvelle api de minetest que j’ai utilisé, normalement le choix de langue se fait côté client, donc si il reste des joueurs anglophones, ils devraient pouvoir voir dans leur langue également sans qu’il n’y ait de changement spécifique à faire côté serveur (pour être clair, les mods en question ne dépendent plus de `intllib` pour gérer la traduction).
Mais c’est vrai que passer le serveur en français permettrait d’avoir les traductions pour les mods qui n’utilisent pas cette api.
Je me suis fait une liste de mods à porter vers la nouvelle api ; je la complète au fur et à mesure que je découvre le jeu via le serveur, mais je n’ai pas forcément beaucoup le temps de jouer, donc si tu penses qu’il y en a à traduire en priorité par rapport à d’autres, je veux bien des suggestions.

**Comment by paly2** [comment]
Ah, parfait, je ne savais pas la nouvelle API permettait un réglage côté client ! Dans ce cas je ne pense pas ajouter intllib
J'ai mis à jour tous les mods, dont ceux concernés par les nouvelles traductions, pour caverealms le dépôt upstream n'est plus mis à jour depuis plusieurs années (c'est pour cela, d'ailleurs, qu'il ne contient pas de .gitrepo, nous n'avons jamais eu besoin de le mettre à jour), donc si la PR n'est pas mergée dans les jours qui viennent j'ajouterai le commit manuellement.
