### ISSUE TITLE
Fix bug duplication livres

### ISSUE THREAD

**Issue by louisroyer** [MT-Eurythmia/Eurythmia-Evolution#14]
J’ai vu que vous avez mis à jour une grande partie des mods récemment, mais vous semblez avoir oublié de mettre à jour [`books`](https://github.com/MT-Eurythmia/Eurythmia-Evolution/tree/master/mods/placeable_books) qui a reçu un correctif empêchant la duplication de livres lorsqu’on les plaçait dans les itemframes. J’imagine que c’est parce que ce mod n’a pas été cloné comme subrepo depuis [everamzah/books](https://github.com/everamzah/books).

**Comment by paly2** [comment]
Merci, c'est corrigé !
