### ISSUE TITLE
[toolranks]A paramétrer ?

### ISSUE THREAD

**Issue by Grossam** [MT-Eurythmia/Eurythmia-Evolution#16]
La nouvelle version de toolranks devrait être paramétrée car les outils atteingnet maintenant leut niveau max au bout de 10 000 nodes. Trop vite donc.

Je propose le niveau max (qu'on peut régler sur 20) à 100 000 nodes, soit un niveau gagné tous les 5K.

**Comment by paly2** [comment]
Réglé, la vitesse d'augmentation des niveaux a été divisée par 10
