### ISSUE TITLE
[travelnet] MAJ liste du réseau

### ISSUE THREAD

**Issue by Xanatos00** [MT-Eurythmia/Eurythmia-Evolution#18]
Lors de l'ajout d'un travelnet à un réseau, la liste ne s'actualise pas sur les précédents travelnet du réseau, à moins de le faire sur chaque travelnet avec "move up" et/ou "move down".

**Comment by paly2** [comment]
Il faut faire un clic gauche sur les travelnet pour les mettre à jour, c'est un comportement volontaire du mod `travelnet` (probablement par souci de simplicité).
